"use client";

import React, { useRef } from "react";
import Link from "next/link";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { TopNav } from "@/components/ui/top-nav";
import { Header } from "@/components/ui/header";
import { Footer } from "@/components/ui/footer";
import { Newsletter } from "@/components/ui/newsletter";
import { FlashBanner } from "@/components/ui/flash-banner";
import { Breadcrumb } from "@/components/ui/breadcrumb";
import { SectionNav, type NavSection } from "@/components/ui/section-nav";
import {
  DollarSign, Shield, Globe, Building2, ArrowRight,
  CheckCircle, Star, Landmark, TrendingUp, Zap, FileText
} from "lucide-react";

gsap.registerPlugin(ScrollTrigger);

const PAGE_SECTIONS: NavSection[] = [
  { id: "overview", label: "Overview" },
  { id: "nc-incentives", label: "NC Incentives" },
  { id: "federal", label: "Federal Programs" },
  { id: "africa-incentives", label: "Africa Incentives" },
  { id: "afdec-navigator", label: "AfDEC Navigator" },
  { id: "eligibility", label: "Check Eligibility" },
];

const NC_INCENTIVES = [
  {
    name: "Job Development Investment Grant (JDIG)",
    authority: "NC Department of Commerce",
    type: "Performance-Based Grant",
    description: "North Carolina's primary economic development tool — grants up to 75% of withholding taxes generated by new positions for up to 12 years. Companies must create new jobs, invest capital, and maintain wage floors to qualify.",
    highlight: "Up to 75% of payroll withholding taxes returned for 12 years",
    eligibility: ["Create 20+ new jobs in Tier 1/2 counties", "Average wage ≥ county average", "Capital investment commitment required"],
    tags: ["Job creation", "Manufacturing", "Technology", "HQ relocation"],
  },
  {
    name: "One North Carolina Fund",
    authority: "NC Governor's Office",
    type: "Discretionary Grant",
    description: "Governor-directed discretionary grants for projects creating significant employment and investment — particularly effective for African enterprises establishing U.S. headquarters or regional offices in NC.",
    highlight: "Discretionary grants $50K–$5M for qualifying projects",
    eligibility: ["Minimum 10 net new jobs", "Wage standard compliance", "Capital investment commitment"],
    tags: ["HQ establishment", "Regional office", "Foreign direct investment"],
  },
  {
    name: "Building Reuse Program",
    authority: "EDPNC",
    type: "Renovation Grant",
    description: "Grants for rehabilitation of existing vacant industrial or commercial buildings — ideal for African diaspora entrepreneurs acquiring underutilized NC properties for manufacturing or services operations.",
    highlight: "Up to $500K for building rehabilitation projects",
    eligibility: ["Vacant building acquisition", "Job creation commitment", "Rural preference counties"],
    tags: ["Real estate", "Manufacturing", "Agribusiness"],
  },
  {
    name: "Site Infrastructure Development Fund",
    authority: "NC Commerce",
    type: "Infrastructure Grant",
    description: "Funds infrastructure improvements — roads, utilities, broadband — adjacent to industrial and business parks. Enables African enterprises to access NC's premier megasite network.",
    highlight: "Infrastructure grants for megasite-adjacent development",
    eligibility: ["Megasite or industrial park proximity", "Significant capital investment"],
    tags: ["Logistics", "Manufacturing", "Gigafactories"],
  },
  {
    name: "NC Research & Development Tax Credit",
    authority: "NC Department of Revenue",
    type: "Tax Credit",
    description: "Tax credit equivalent to 25% of qualifying R&D expenditures in NC — one of the most generous R&D incentive structures in the southeastern U.S. Ideal for life sciences, defense tech, and fintech R&D operations.",
    highlight: "25% credit on qualifying R&D expenditures",
    eligibility: ["R&D activity in NC", "Qualifying expenditures documentation"],
    tags: ["Life sciences", "Tech", "Defense", "Fintech R&D"],
  },
  {
    name: "Workforce Training Incentives",
    authority: "Community College System",
    type: "Training Grant",
    description: "Free customized workforce training through the NC Community College system for new or expanding businesses — the #1 workforce training program in the U.S. Up to $2,500 per employee in direct training subsidies.",
    highlight: "Up to $2,500 per employee in training subsidies",
    eligibility: ["New or expanding NC operations", "Qualifying net new jobs"],
    tags: ["All industries", "Skills training", "Workforce development"],
  },
];

const FEDERAL_PROGRAMS = [
  {
    name: "Opportunity Zones (OZ)",
    authority: "U.S. Treasury / IRS",
    description: "58 designated Opportunity Zones in North Carolina offer capital gains tax deferral, reduction, and elimination for qualifying investments. AfDEC has mapped all 58 NC OZs with African investor suitability scores.",
    highlight: "Capital gains tax elimination on 10-year OZ investments",
    tags: ["Real estate", "Manufacturing", "All sectors"],
  },
  {
    name: "EB-5 Immigrant Investor Program",
    authority: "USCIS",
    description: "African HNW investors seeking U.S. permanent residency through $800K–$1.05M investments in Regional Center projects creating 10+ U.S. jobs. AfDEC provides complete EB-5 navigator services.",
    highlight: "$800K minimum investment for green card pathway",
    tags: ["Immigration pathway", "Real estate", "Job creation"],
  },
  {
    name: "USAID Trade & Investment Programs",
    authority: "USAID / DFC",
    description: "U.S. Development Finance Corporation (DFC) provides guarantees, direct loans, and political risk insurance for U.S. companies investing in Africa. AfDEC facilitates DFC applications for NC–Africa corridor projects.",
    highlight: "DFC guarantees up to $1B for Africa-related projects",
    tags: ["Africa expansion", "Risk mitigation", "Trade finance"],
  },
  {
    name: "EXIM Bank Trade Finance",
    authority: "Export-Import Bank of the U.S.",
    description: "Export financing, guarantees, and insurance for NC companies exporting to Africa — covering up to 85% of contract value. Particularly strong for capital goods, agricultural equipment, and technology exports.",
    highlight: "Up to 85% export financing coverage",
    tags: ["NC exports to Africa", "Capital goods", "Agriculture"],
  },
];

const AFRICA_INCENTIVES = [
  {
    name: "AfCFTA Preferential Tariffs",
    authority: "African Union / AfCFTA",
    description: "The African Continental Free Trade Area eliminates tariffs on 90% of goods traded across 47 AU member states. AfDEC navigates AfCFTA HS code classification and certificate of origin requirements for NC exporters.",
    highlight: "Tariff elimination on 90% of goods across 47 nations",
    region: "Pan-African",
  },
  {
    name: "Afreximbank Trade Finance",
    authority: "African Export-Import Bank",
    description: "Afreximbank provides trade finance instruments — letters of credit, supply chain finance, commodity finance — for transactions between NC companies and African counterparts. AfDEC is an Afreximbank correspondent partner.",
    highlight: "Structured trade finance across 54 African markets",
    region: "Pan-African",
  },
  {
    name: "Nigeria Investment Promotion Council (NIPC)",
    authority: "Government of Nigeria",
    description: "Pioneer Status tax holidays (3–5 years), import duty waivers on plant & equipment, and 100% foreign ownership in all sectors. AfDEC facilitates NIPC applications for NC companies entering Nigeria.",
    highlight: "3-5 year tax holiday for pioneer companies",
    region: "Nigeria",
  },
  {
    name: "Kenya Investment Authority (KenInvest)",
    authority: "Government of Kenya",
    description: "Single-customer service window for investment licensing, land acquisition, immigration visas, and fiscal incentives. EPZ status for qualifying export-oriented manufacturers.",
    highlight: "Fast-track investment licensing in 3 business days",
    region: "Kenya",
  },
  {
    name: "GIPC (Ghana Investment Promotion Centre)",
    authority: "Government of Ghana",
    description: "Ghana's investment gateway — guarantees, free repatriation of profits, import duty concessions, and the most liberal foreign ownership rules in West Africa. NC diaspora investors receive accelerated processing.",
    highlight: "Free repatriation of profits, 100% foreign ownership",
    region: "Ghana",
  },
];

export default function SovereignIncentivesPage() {
  const ncRef = useRef<HTMLDivElement>(null);
  const africaRef = useRef<HTMLDivElement>(null);

  useGSAP(() => {
    gsap.fromTo(".nc-card", { y: 30, opacity: 0 },
      { y: 0, opacity: 1, stagger: 0.1, duration: 0.5, ease: "power3.out",
        scrollTrigger: { trigger: ncRef.current, start: "top 85%" } }
    );
    gsap.fromTo(".africa-card", { y: 30, opacity: 0 },
      { y: 0, opacity: 1, stagger: 0.1, duration: 0.5, ease: "power3.out",
        scrollTrigger: { trigger: africaRef.current, start: "top 85%" } }
    );
  }, {});

  return (
    <main className="min-h-screen bg-zinc-950 font-sans selection:bg-blue-500/30 selection:text-blue-200">
      <div className="sticky top-0 z-[100] w-full flex flex-col" data-nav-id="main-nav">
        <TopNav />
        <FlashBanner />
        <Header />
      </div>
      <Breadcrumb />
      <SectionNav sections={PAGE_SECTIONS} accentColor="emerald" />

      {/* ── Hero ── */}
      <section id="overview" className="relative bg-zinc-950 border-b border-zinc-800/50 overflow-hidden">
        <div className="absolute inset-0 opacity-25"
          style={{ backgroundImage: "url('https://images.unsplash.com/photo-1554224155-6726b3ff858f?q=80&w=2670&auto=format&fit=crop')", backgroundSize: "cover", backgroundPosition: "center" }} />
        <div className="absolute inset-0 bg-gradient-to-r from-zinc-950 via-zinc-950/88 to-zinc-950/30" />
        <div className="absolute bottom-0 left-0 right-0 h-32 bg-gradient-to-t from-zinc-950 to-transparent" />
        <div className="max-w-[1600px] mx-auto px-6 lg:px-12 py-24 md:py-32 relative z-10">
          <div className="inline-flex items-center gap-2 px-3 py-1 bg-zinc-800/80 border border-zinc-700/50 mb-6 rounded-full backdrop-blur-md">
            <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" />
            <span className="text-[11px] font-bold tracking-[0.2em] text-zinc-400 uppercase">Strategic Footprint · Incentives</span>
          </div>
          <h1 className="text-4xl md:text-5xl lg:text-6xl font-black text-white tracking-tight leading-[1.1] max-w-4xl mb-6">
            Sovereign Incentives<br className="hidden md:block" /> & Grants
          </h1>
          <p className="text-lg md:text-xl text-zinc-400 max-w-2xl leading-relaxed font-medium mb-10">
            A comprehensive navigator to North Carolina state incentives, U.S. federal programs, and African investment promotion authority grants — curated and facilitated by AfDEC for transatlantic enterprise expansion.
          </p>
          <div className="flex flex-wrap gap-3 mb-10">
            {["NC State Grants", "Federal Programs", "AfCFTA Benefits", "EB-5 Pathway", "Afreximbank Finance"].map((tag) => (
              <span key={tag} className="text-[11px] font-bold text-emerald-300 bg-emerald-500/10 border border-emerald-500/20 px-3 py-1.5 rounded-full uppercase tracking-wider">
                {tag}
              </span>
            ))}
          </div>
          <Link href="#eligibility" className="inline-flex items-center gap-2 bg-emerald-600 hover:bg-emerald-500 text-white text-sm font-bold tracking-widest uppercase px-8 py-4 rounded-sm transition-all">
            <span>Check My Eligibility</span>
            <ArrowRight className="w-4 h-4" />
          </Link>
        </div>
        <div className="absolute bottom-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-emerald-500/30 to-transparent" />
      </section>

      {/* ── AfDEC Role ── */}
      <section className="bg-zinc-900/30 border-b border-zinc-800/30 py-14">
        <div className="max-w-[1600px] mx-auto px-6 lg:px-12">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {[
              { icon: FileText, title: "Identification", body: "AfDEC maps the full incentive landscape — federal, state, and Africa-side — to your specific enterprise profile, sector, and expansion plan." },
              { icon: Shield, title: "Application Support", body: "Our team prepares, submits, and follows up on JDIG, GIPC, KenInvest, and OZ applications on behalf of member enterprises." },
              { icon: TrendingUp, title: "Optimization", body: "We stack applicable programs — combining NC state grants, OZ tax deferral, and AfCFTA preferential tariffs to maximize your effective incentive package." },
            ].map((item) => {
              const Icon = item.icon;
              return (
                <div key={item.title} className="flex gap-5 p-6 bg-zinc-900/30 border border-zinc-800/50 rounded-sm">
                  <div className="w-10 h-10 rounded-sm bg-emerald-500/10 flex items-center justify-center shrink-0">
                    <Icon className="w-5 h-5 text-emerald-400" />
                  </div>
                  <div>
                    <h3 className="text-white font-bold text-sm mb-1">{item.title}</h3>
                    <p className="text-zinc-500 text-[13px] leading-relaxed">{item.body}</p>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* ── NC Incentives ── */}
      <section id="nc-incentives" ref={ncRef} className="bg-zinc-950 py-24 border-b border-zinc-800/30">
        <div className="max-w-[1600px] mx-auto px-6 lg:px-12">
          <div className="mb-16">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-8 h-px bg-blue-500" />
              <span className="text-[11px] font-bold tracking-[0.2em] text-blue-400 uppercase">North Carolina</span>
            </div>
            <h2 className="text-3xl md:text-4xl font-black text-white">NC State Incentives</h2>
            <p className="text-zinc-400 mt-4 max-w-2xl text-[15px]">
              North Carolina offers one of the most competitive incentive environments in the United States — with the lowest corporate tax rate (2.5%) and a suite of performance-based grants that reward job creation and capital investment.
            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {NC_INCENTIVES.map((item) => (
              <div key={item.name} className="nc-card bg-zinc-900/30 border border-zinc-800/50 rounded-sm p-7 hover:border-blue-500/20 transition-all duration-300">
                <div className="flex items-start justify-between mb-3">
                  <div>
                    <div className="text-[10px] font-bold text-zinc-600 uppercase tracking-widest mb-1">{item.type} · {item.authority}</div>
                    <h3 className="text-white font-bold text-[16px]">{item.name}</h3>
                  </div>
                  <Star className="w-4 h-4 text-blue-400/40 shrink-0" />
                </div>
                <p className="text-zinc-400 text-[13px] leading-relaxed mb-4">{item.description}</p>
                <div className="bg-blue-950/30 border border-blue-900/30 rounded-sm px-4 py-3 mb-4">
                  <div className="flex items-center gap-2">
                    <Zap className="w-3.5 h-3.5 text-blue-400 shrink-0" />
                    <span className="text-blue-300 text-[12px] font-bold">{item.highlight}</span>
                  </div>
                </div>
                <div className="space-y-1.5 mb-4">
                  {item.eligibility.map((e) => (
                    <div key={e} className="flex items-center gap-2">
                      <CheckCircle className="w-3 h-3 text-emerald-500 shrink-0" />
                      <span className="text-[12px] text-zinc-400">{e}</span>
                    </div>
                  ))}
                </div>
                <div className="flex flex-wrap gap-1.5">
                  {item.tags.map((tag) => (
                    <span key={tag} className="text-[10px] font-bold text-zinc-500 bg-zinc-800/60 px-2 py-0.5 rounded-sm border border-zinc-700/50 uppercase tracking-wider">{tag}</span>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Federal Programs ── */}
      <section id="federal" className="bg-[#080808] py-24 border-b border-zinc-800/30">
        <div className="max-w-[1600px] mx-auto px-6 lg:px-12">
          <div className="mb-16">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-8 h-px bg-purple-500" />
              <span className="text-[11px] font-bold tracking-[0.2em] text-purple-400 uppercase">Federal</span>
            </div>
            <h2 className="text-3xl md:text-4xl font-black text-white">U.S. Federal Programs</h2>
            <p className="text-zinc-400 mt-4 max-w-2xl text-[15px]">
              Federal incentive programs that complement NC state grants — unlocking capital gains deferral, immigration pathways, export financing, and Africa-focused development finance.
            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {FEDERAL_PROGRAMS.map((prog) => (
              <div key={prog.name} className="bg-zinc-900/30 border border-zinc-800/50 rounded-sm p-7 hover:border-purple-500/20 transition-all duration-300">
                <div className="text-[10px] font-bold text-zinc-600 uppercase tracking-widest mb-1">{prog.authority}</div>
                <h3 className="text-white font-bold text-[16px] mb-3">{prog.name}</h3>
                <p className="text-zinc-400 text-[13px] leading-relaxed mb-4">{prog.description}</p>
                <div className="bg-purple-950/30 border border-purple-900/30 rounded-sm px-4 py-3 mb-4">
                  <div className="flex items-center gap-2">
                    <Landmark className="w-3.5 h-3.5 text-purple-400 shrink-0" />
                    <span className="text-purple-300 text-[12px] font-bold">{prog.highlight}</span>
                  </div>
                </div>
                <div className="flex flex-wrap gap-1.5">
                  {prog.tags.map((tag) => (
                    <span key={tag} className="text-[10px] font-bold text-zinc-500 bg-zinc-800/60 px-2 py-0.5 rounded-sm border border-zinc-700/50 uppercase tracking-wider">{tag}</span>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Africa Incentives ── */}
      <section id="africa-incentives" ref={africaRef} className="bg-zinc-950 py-24 border-b border-zinc-800/30">
        <div className="max-w-[1600px] mx-auto px-6 lg:px-12">
          <div className="mb-16">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-8 h-px bg-emerald-500" />
              <span className="text-[11px] font-bold tracking-[0.2em] text-emerald-400 uppercase">Africa-Side</span>
            </div>
            <h2 className="text-3xl md:text-4xl font-black text-white">African Sovereign Incentives</h2>
            <p className="text-zinc-400 mt-4 max-w-2xl text-[15px]">
              AfDEC maps Africa-side incentives — from AfCFTA trade preferences to country-specific investment promotion authority grants — and facilitates applications on behalf of NC enterprises expanding into Africa.
            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {AFRICA_INCENTIVES.map((item) => (
              <div key={item.name} className="africa-card bg-zinc-900/20 border border-zinc-800/40 rounded-sm p-7 hover:border-emerald-500/20 transition-all duration-300">
                <div className="flex items-center justify-between mb-3">
                  <div className="text-[10px] font-bold text-zinc-600 uppercase tracking-widest">{item.authority}</div>
                  <span className="text-[9px] font-bold text-emerald-400 bg-emerald-500/10 border border-emerald-500/20 px-2 py-0.5 rounded-full uppercase tracking-widest">{item.region}</span>
                </div>
                <h3 className="text-white font-bold text-[15px] mb-3">{item.name}</h3>
                <p className="text-zinc-400 text-[13px] leading-relaxed mb-4">{item.description}</p>
                <div className="bg-emerald-950/30 border border-emerald-900/30 rounded-sm px-4 py-3">
                  <div className="flex items-center gap-2">
                    <Globe className="w-3.5 h-3.5 text-emerald-400 shrink-0" />
                    <span className="text-emerald-300 text-[12px] font-bold">{item.highlight}</span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── AfDEC Navigator ── */}
      <section id="afdec-navigator" className="bg-[#080808] py-24 border-b border-zinc-800/30">
        <div className="max-w-[1600px] mx-auto px-6 lg:px-12">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">
            <div>
              <div className="flex items-center gap-3 mb-4">
                <div className="w-8 h-px bg-amber-500" />
                <span className="text-[11px] font-bold tracking-[0.2em] text-amber-400 uppercase">AfDEC Navigator</span>
              </div>
              <h2 className="text-3xl md:text-4xl font-black text-white mb-6">We Navigate the System for You</h2>
              <p className="text-zinc-400 text-[15px] leading-relaxed mb-8">
                Sovereign incentives and grant programs are complex, time-sensitive, and jurisdiction-specific. AfDEC's Navigator Service acts as your dedicated incentives consultant — identifying, stacking, and applying for every applicable program on your behalf.
              </p>
              <div className="space-y-4 mb-8">
                {[
                  "Full incentive audit mapped to your enterprise profile",
                  "JDIG, One NC Fund, and EDPNC application preparation",
                  "KenInvest, GIPC, and NIPC applications for Africa expansion",
                  "Opportunity Zone investment pathway structuring",
                  "EB-5 investor visa coordination with immigration counsel",
                  "AfCFTA certificate of origin and preferential tariff navigation",
                ].map((item) => (
                  <div key={item} className="flex items-start gap-3">
                    <CheckCircle className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
                    <span className="text-zinc-300 text-[14px]">{item}</span>
                  </div>
                ))}
              </div>
              <Link href="/contact" className="inline-flex items-center gap-2 bg-amber-600 hover:bg-amber-500 text-white text-sm font-bold tracking-widest uppercase px-8 py-4 rounded-sm transition-all">
                <span>Request Navigator Service</span>
                <ArrowRight className="w-4 h-4" />
              </Link>
            </div>
            <div className="bg-zinc-900/30 border border-zinc-800/50 rounded-xl p-8">
              <div className="text-[11px] font-bold text-zinc-500 uppercase tracking-widest mb-6">Typical Incentive Package (NC Enterprise Expansion)</div>
              <div className="space-y-4">
                {[
                  { label: "JDIG Grant (12-year, 50 jobs)", value: "$4.2M", color: "text-blue-400" },
                  { label: "Workforce Training Subsidy", value: "$125K", color: "text-emerald-400" },
                  { label: "OZ Capital Gains Deferral", value: "$380K", color: "text-purple-400" },
                  { label: "R&D Tax Credit (Year 1)", value: "$210K", color: "text-amber-400" },
                  { label: "JDIG Other Half (Utility Fund)", value: "$1.1M", color: "text-blue-400" },
                ].map((item) => (
                  <div key={item.label} className="flex items-center justify-between py-3 border-b border-zinc-800/50">
                    <span className="text-zinc-400 text-[13px]">{item.label}</span>
                    <span className={`font-black text-lg ${item.color}`}>{item.value}</span>
                  </div>
                ))}
                <div className="flex items-center justify-between pt-2">
                  <span className="text-white font-bold text-sm">Total Incentive Value</span>
                  <span className="font-black text-2xl text-white">$6.0M+</span>
                </div>
              </div>
              <p className="text-zinc-700 text-[10px] mt-4">*Illustrative example based on a 50-job, $10M capital investment project in a Tier 2 NC county. Actual amounts vary.</p>
            </div>
          </div>
        </div>
      </section>

      {/* ── Eligibility CTA ── */}
      <section id="eligibility" className="bg-zinc-950 py-24">
        <div className="max-w-[1600px] mx-auto px-6 lg:px-12">
          <div className="bg-gradient-to-br from-emerald-950/30 to-zinc-900/40 border border-emerald-900/20 rounded-xl p-10 md:p-14 relative overflow-hidden text-center">
            <div className="absolute -left-20 -top-20 w-72 h-72 bg-emerald-600/5 rounded-full blur-[100px]" />
            <div className="relative z-10">
              <DollarSign className="w-10 h-10 text-emerald-400 mx-auto mb-4" />
              <h2 className="text-3xl md:text-4xl font-black text-white mb-4">Check Your Incentive Eligibility</h2>
              <p className="text-zinc-400 text-[15px] max-w-xl mx-auto mb-8">
                Tell us about your enterprise — sector, headcount, investment size, and target market — and AfDEC will map every applicable NC, federal, and Africa-side incentive program to your profile within 48 hours.
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <Link href="/contact" className="inline-flex items-center justify-center gap-2 bg-emerald-600 hover:bg-emerald-500 text-white text-sm font-bold tracking-widest uppercase px-8 py-4 rounded-sm transition-all">
                  <span>Get My Incentive Map</span>
                  <ArrowRight className="w-4 h-4" />
                </Link>
                <Link href="/why-nc" className="inline-flex items-center justify-center gap-2 border border-zinc-700 hover:border-zinc-500 text-zinc-300 hover:text-white text-sm font-bold tracking-widest uppercase px-8 py-4 rounded-sm transition-all">
                  Explore North Carolina
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>

      <div className="relative bg-zinc-950 overflow-hidden">
        <div className="absolute inset-0 bg-cover bg-center opacity-15 mix-blend-overlay pointer-events-none"
          style={{ backgroundImage: "url('https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=2070&auto=format&fit=crop')" }} />
        <Newsletter />
        <Footer />
      </div>
    </main>
  );
}
